// Metric
export const metricModalStyle = {
  overlay: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    zIndex: 1000,
  },
  content: {
    position: 'none',
    width: '50%',
  },
};

export const METRIC_DATA_FETCH_ERROR = 'METRIC_DATA_FETCH_ERROR';
export const METRIC_DATA_FETCHED = 'METRIC_DATA_FETCHED';
export const METRIC_DATA_FETCHING = 'METRIC_DATA_FETCHING';
export const METRIC_INIT = 'METRIC_INIT';
export const METRIC_FILTER_CHANGED = 'METRIC_FILTER_CHANGED';
export const METRIC_FILTER_FETCH_ERROR = 'METRIC_FILTER_FETCH_ERROR';
export const METRIC_FILTER_FETCHED = 'METRIC_FILTER_FETCHED';
export const METRIC_FILTER_FETCHING = 'METRIC_FILTER_FETCHING';
export const METRIC_MODAL_CLOSE = 'METRIC_MODAL_CLOSE';
export const METRIC_MODAL_OPEN = 'METRIC_MODAL_OPEN';
export const METRIC_OVERVIEW_API_FETCH_ERROR = 'METRIC_OVERVIEW_API_FETCH_ERROR';
export const METRIC_OVERVIEW_API_FETCHED = 'METRIC_OVERVIEW_API_FETCHED';
export const METRIC_OVERVIEW_API_FETCHING = 'METRIC_OVERVIEW_API_FETCHING';
export const METRIC_OVERVIEW_API_SELECTED = 'METRIC_OVERVIEW_API_SELECTED';
export const METRIC_OVERVIEW_API_DETAIL_FETCH_ERROR = 'METRIC_OVERVIEW_API_DETAIL_FETCH_ERROR';
export const METRIC_OVERVIEW_API_DETAIL_FETCHED = 'METRIC_OVERVIEW_API_DETAIL_FETCHED';
export const METRIC_OVERVIEW_API_DETAIL_FETCHING = 'METRIC_OVERVIEW_API_DETAIL_FETCHING';
export const METRIC_OVERVIEW_CPU_FETCH_ERROR = 'METRIC_OVERVIEW_CPU_FETCH_ERROR';
export const METRIC_OVERVIEW_CPU_FETCHED = 'METRIC_OVERVIEW_CPU_FETCHED';
export const METRIC_OVERVIEW_CPU_FETCHING = 'METRIC_OVERVIEW_CPU_FETCHING';
export const METRIC_OVERVIEW_CPU_SELECTED = 'METRIC_OVERVIEW_CPU_SELECTED';
export const METRIC_OVERVIEW_CRUMB_SELECTED = 'METRIC_OVERVIEW_CRUMB_SELECTED';
export const METRIC_OVERVIEW_REALTIME_FETCHED = 'METRIC_OVERVIEW_REALTIME_FETCHED';
export const METRIC_TIME_CHANGED = 'METRIC_TIME_CHANGED';
