// Metric
export const METRIC_DATA_FETCH_ERROR = 'METRIC_DATA_FETCH_ERROR';
export const METRIC_DATA_FETCHED = 'METRIC_DATA_FETCHED';
export const METRIC_DATA_FETCHING = 'METRIC_DATA_FETCHING';
export const METRIC_INIT = 'METRIC_INIT';
export const METRIC_FILTER_CHANGED = 'METRIC_FILTER_CHANGED';
export const METRIC_FILTER_FETCH_ERROR = 'METRIC_FILTER_FETCH_ERROR';
export const METRIC_FILTER_FETCHED = 'METRIC_FILTER_FETCHED';
export const METRIC_FILTER_FETCHING = 'METRIC_FILTER_FETCHING';
export const METRIC_OVERVIEW_API_FETCH_ERROR = 'METRIC_OVERVIEW_API_FETCH_ERROR';
export const METRIC_OVERVIEW_API_FETCHED = 'METRIC_OVERVIEW_API_FETCHED';
export const METRIC_OVERVIEW_API_FETCHING = 'METRIC_OVERVIEW_API_FETCHING';
export const METRIC_OVERVIEW_CPU_FETCH_ERROR = 'METRIC_OVERVIEW_CPU_FETCH_ERROR';
export const METRIC_OVERVIEW_CPU_FETCHED = 'METRIC_OVERVIEW_CPU_FETCHED';
export const METRIC_OVERVIEW_CPU_FETCHING = 'METRIC_OVERVIEW_CPU_FETCHING';
export const METRIC_OVERVIEW_CPU_SELECTED = 'METRIC_OVERVIEW_CPU_SELECTED';
export const METRIC_TIME_CHANGED = 'METRIC_TIME_CHANGED';
