// Metric
export const METRIC_CLEAR = 'METRIC_CLEAR';
export const METRIC_FETCHED = 'METRIC_FETCHED';
export const METRIC_FETCHING = 'METRIC_FETCHING';
export const METRIC_FETCH_ERROR = 'METRIC_FETCH_ERROR';
