export const settingsModalStyle = {
  overlay: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    position: 'absolute',
    width: '100%',
    zIndex: 1000,
  },
  content: {
    position: 'none',
    width: '300px',
  },
};

// Member
export const SETTINGS_MEMBER_FETCH_ERROR = 'SETTINGS_MEMBER_FETCH_ERROR';
export const SETTINGS_MEMBER_FETCHED = 'SETTINGS_MEMBER_FETCHED';
export const SETTINGS_MEMBER_FETCHING = 'SETTINGS_MEMBER_FETCHING';
export const SETTINGS_MEMBER_INIT = 'SETTINGS_MEMBER_INIT';
export const SETTINGS_MEMBER_MODAL_CLOSE = 'SETTINGS_MEMBER_MODAL_CLOSE';
export const SETTINGS_MEMBER_MODAL_FETCH_ERROR = 'SETTINGS_MEMBER_MODAL_FETCH_ERROR';
export const SETTINGS_MEMBER_MODAL_FETCHED = 'SETTINGS_MEMBER_MODAL_FETCHED';
export const SETTINGS_MEMBER_MODAL_FETCHING = 'SETTINGS_MEMBER_MODAL_FETCHING';
export const SETTINGS_MEMBER_MODAL_OPEN = 'SETTINGS_MEMBER_MODAL_OPEN';

// Notification
export const SETTINGS_NOTIFICATION_FETCH_ERROR = 'SETTINGS_NOTIFICATION_FETCH_ERROR';
export const SETTINGS_NOTIFICATION_FETCHED = 'SETTINGS_NOTIFICATION_FETCHED';
export const SETTINGS_NOTIFICATION_FETCHING = 'SETTINGS_NOTIFICATION_FETCHING';
export const SETTINGS_NOTIFICATION_INIT = 'SETTINGS_NOTIFICATION_INIT';
export const SETTINGS_NOTIFICATION_MODAL_CLOSE = 'SETTINGS_NOTIFICATION_MODAL_CLOSE';
export const SETTINGS_NOTIFICATION_MODAL_FETCH_ERROR = 'SETTINGS_NOTIFICATION_MODAL_FETCH_ERROR';
export const SETTINGS_NOTIFICATION_MODAL_FETCHED = 'SETTINGS_NOTIFICATION_MODAL_FETCHED';
export const SETTINGS_NOTIFICATION_MODAL_FETCHING = 'SETTINGS_NOTIFICATION_MODAL_FETCHING';
export const SETTINGS_NOTIFICATION_MODAL_OPEN = 'SETTINGS_NOTIFICATION_MODAL_OPEN';
