// Projects
export const PROJECTS_FETCH_ERROR = 'PROJECTS_FETCH_ERROR';
export const PROJECTS_FETCHING = 'PROJECTS_FETCHING';
export const PROJECTS_FETCHED = 'PROJECTS_FETCHED';
export const PROJECTS_MODAL_OPEN = 'PROJECTS_MODAL_OPEN';
export const PROJECTS_MODAL_CLOSE = 'PROJECTS_MODAL_CLOSE';
